version: '3'

services:
  postgresdb:
    container_name: postgresdb
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
  api:
    container_name: api
    image: drone-image-processing-api
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgresdb
    ports:
      - "8080:8080"
    environment:
      DIP_DB_PASSWORD: postgres
      DB_HOST: postgresdb
      DB_NAME: postgres
      DB_PORT: 5432
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
